### ISSUE TITLE
Question: Are you planning to release the latest version in maven ?

### ISSUE THREAD

**Issue by madhu314** [prolificinteractive/HouseOfCards#4]
Maven has version 1.0.0 which does not contain latest commits of JCB card types.

Are you planning to release any new version based out of latest commits ?

**Comment by quentin41500** [comment]
Sorry for the late reply @madhu314, I will be publishing `1.0.1` in the near future. Stay tuned!

**Comment by quentin41500** [comment]
@madhu314 https://github.com/prolificinteractive/HouseOfCards/releases/tag/v1.0.1
